version: '3.2'
 
services:
  rancher:
    image: rancher/rancher:latest
    entrypoint: ["entrypoint.sh", "--no-cacerts"]
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/centos/certificates/server.pem:/etc/rancher/ssl/cert.pem
      - /home/centos/certificates/private.pem:/etc/rancher/ssl/key.pem
      - /data:/var/lib/rancher
